// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "dakhou/todo/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeGetHandler(m, endpoints, options["Get"])
	makeAddHandler(m, endpoints, options["Add"])
	makeSetCompleteHandler(m, endpoints, options["SetComplete"])
	makeRemoveCompleteHandler(m, endpoints, options["RemoveComplete"])
	makeDeleteHandler(m, endpoints, options["Delete"])
	makeUpdateHandler(m, endpoints, options["Update"])
	makeSetStarHandler(m, endpoints, options["SetStar"])
	makeGetChildrenHandler(m, endpoints, options["GetChildren"])
	makeGetCategoryHandler(m, endpoints, options["GetCategory"])
	makeAddCategoryHandler(m, endpoints, options["AddCategory"])
	makeUpdateCategoryHandler(m, endpoints, options["UpdateCategory"])
	makeDeleteCategoryHandler(m, endpoints, options["DeleteCategory"])
	makeGetCatChildesHandler(m, endpoints, options["GetCatChildes"])
	return m
}
