// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo/pkg/grpc/pb/todo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReply) Reset()         { *m = GetReply{} }
func (m *GetReply) String() string { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()    {}
func (*GetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{1}
}

func (m *GetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReply.Unmarshal(m, b)
}
func (m *GetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReply.Marshal(b, m, deterministic)
}
func (m *GetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReply.Merge(m, src)
}
func (m *GetReply) XXX_Size() int {
	return xxx_messageInfo_GetReply.Size(m)
}
func (m *GetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetReply proto.InternalMessageInfo

type AddRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{2}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

type AddReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReply) Reset()         { *m = AddReply{} }
func (m *AddReply) String() string { return proto.CompactTextString(m) }
func (*AddReply) ProtoMessage()    {}
func (*AddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{3}
}

func (m *AddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReply.Unmarshal(m, b)
}
func (m *AddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReply.Marshal(b, m, deterministic)
}
func (m *AddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReply.Merge(m, src)
}
func (m *AddReply) XXX_Size() int {
	return xxx_messageInfo_AddReply.Size(m)
}
func (m *AddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddReply proto.InternalMessageInfo

type SetCompleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCompleteRequest) Reset()         { *m = SetCompleteRequest{} }
func (m *SetCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*SetCompleteRequest) ProtoMessage()    {}
func (*SetCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{4}
}

func (m *SetCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCompleteRequest.Unmarshal(m, b)
}
func (m *SetCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCompleteRequest.Marshal(b, m, deterministic)
}
func (m *SetCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCompleteRequest.Merge(m, src)
}
func (m *SetCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_SetCompleteRequest.Size(m)
}
func (m *SetCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCompleteRequest proto.InternalMessageInfo

type SetCompleteReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCompleteReply) Reset()         { *m = SetCompleteReply{} }
func (m *SetCompleteReply) String() string { return proto.CompactTextString(m) }
func (*SetCompleteReply) ProtoMessage()    {}
func (*SetCompleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{5}
}

func (m *SetCompleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCompleteReply.Unmarshal(m, b)
}
func (m *SetCompleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCompleteReply.Marshal(b, m, deterministic)
}
func (m *SetCompleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCompleteReply.Merge(m, src)
}
func (m *SetCompleteReply) XXX_Size() int {
	return xxx_messageInfo_SetCompleteReply.Size(m)
}
func (m *SetCompleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCompleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetCompleteReply proto.InternalMessageInfo

type RemoveCompleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCompleteRequest) Reset()         { *m = RemoveCompleteRequest{} }
func (m *RemoveCompleteRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveCompleteRequest) ProtoMessage()    {}
func (*RemoveCompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{6}
}

func (m *RemoveCompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCompleteRequest.Unmarshal(m, b)
}
func (m *RemoveCompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCompleteRequest.Marshal(b, m, deterministic)
}
func (m *RemoveCompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCompleteRequest.Merge(m, src)
}
func (m *RemoveCompleteRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveCompleteRequest.Size(m)
}
func (m *RemoveCompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCompleteRequest proto.InternalMessageInfo

type RemoveCompleteReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCompleteReply) Reset()         { *m = RemoveCompleteReply{} }
func (m *RemoveCompleteReply) String() string { return proto.CompactTextString(m) }
func (*RemoveCompleteReply) ProtoMessage()    {}
func (*RemoveCompleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{7}
}

func (m *RemoveCompleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCompleteReply.Unmarshal(m, b)
}
func (m *RemoveCompleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCompleteReply.Marshal(b, m, deterministic)
}
func (m *RemoveCompleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCompleteReply.Merge(m, src)
}
func (m *RemoveCompleteReply) XXX_Size() int {
	return xxx_messageInfo_RemoveCompleteReply.Size(m)
}
func (m *RemoveCompleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCompleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCompleteReply proto.InternalMessageInfo

type DeleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

type DeleteReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{9}
}

func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (m *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(m, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

type UpdateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{10}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

type UpdateReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReply) Reset()         { *m = UpdateReply{} }
func (m *UpdateReply) String() string { return proto.CompactTextString(m) }
func (*UpdateReply) ProtoMessage()    {}
func (*UpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{11}
}

func (m *UpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReply.Unmarshal(m, b)
}
func (m *UpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReply.Marshal(b, m, deterministic)
}
func (m *UpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReply.Merge(m, src)
}
func (m *UpdateReply) XXX_Size() int {
	return xxx_messageInfo_UpdateReply.Size(m)
}
func (m *UpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReply proto.InternalMessageInfo

type SetStarRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStarRequest) Reset()         { *m = SetStarRequest{} }
func (m *SetStarRequest) String() string { return proto.CompactTextString(m) }
func (*SetStarRequest) ProtoMessage()    {}
func (*SetStarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{12}
}

func (m *SetStarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStarRequest.Unmarshal(m, b)
}
func (m *SetStarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStarRequest.Marshal(b, m, deterministic)
}
func (m *SetStarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStarRequest.Merge(m, src)
}
func (m *SetStarRequest) XXX_Size() int {
	return xxx_messageInfo_SetStarRequest.Size(m)
}
func (m *SetStarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetStarRequest proto.InternalMessageInfo

type SetStarReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetStarReply) Reset()         { *m = SetStarReply{} }
func (m *SetStarReply) String() string { return proto.CompactTextString(m) }
func (*SetStarReply) ProtoMessage()    {}
func (*SetStarReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{13}
}

func (m *SetStarReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetStarReply.Unmarshal(m, b)
}
func (m *SetStarReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetStarReply.Marshal(b, m, deterministic)
}
func (m *SetStarReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetStarReply.Merge(m, src)
}
func (m *SetStarReply) XXX_Size() int {
	return xxx_messageInfo_SetStarReply.Size(m)
}
func (m *SetStarReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetStarReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetStarReply proto.InternalMessageInfo

type GetChildrenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChildrenRequest) Reset()         { *m = GetChildrenRequest{} }
func (m *GetChildrenRequest) String() string { return proto.CompactTextString(m) }
func (*GetChildrenRequest) ProtoMessage()    {}
func (*GetChildrenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{14}
}

func (m *GetChildrenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChildrenRequest.Unmarshal(m, b)
}
func (m *GetChildrenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChildrenRequest.Marshal(b, m, deterministic)
}
func (m *GetChildrenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChildrenRequest.Merge(m, src)
}
func (m *GetChildrenRequest) XXX_Size() int {
	return xxx_messageInfo_GetChildrenRequest.Size(m)
}
func (m *GetChildrenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChildrenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChildrenRequest proto.InternalMessageInfo

type GetChildrenReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChildrenReply) Reset()         { *m = GetChildrenReply{} }
func (m *GetChildrenReply) String() string { return proto.CompactTextString(m) }
func (*GetChildrenReply) ProtoMessage()    {}
func (*GetChildrenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{15}
}

func (m *GetChildrenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChildrenReply.Unmarshal(m, b)
}
func (m *GetChildrenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChildrenReply.Marshal(b, m, deterministic)
}
func (m *GetChildrenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChildrenReply.Merge(m, src)
}
func (m *GetChildrenReply) XXX_Size() int {
	return xxx_messageInfo_GetChildrenReply.Size(m)
}
func (m *GetChildrenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChildrenReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetChildrenReply proto.InternalMessageInfo

type GetCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{16}
}

func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(m, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

type GetCategoryReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryReply) Reset()         { *m = GetCategoryReply{} }
func (m *GetCategoryReply) String() string { return proto.CompactTextString(m) }
func (*GetCategoryReply) ProtoMessage()    {}
func (*GetCategoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{17}
}

func (m *GetCategoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryReply.Unmarshal(m, b)
}
func (m *GetCategoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryReply.Marshal(b, m, deterministic)
}
func (m *GetCategoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryReply.Merge(m, src)
}
func (m *GetCategoryReply) XXX_Size() int {
	return xxx_messageInfo_GetCategoryReply.Size(m)
}
func (m *GetCategoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryReply proto.InternalMessageInfo

type AddCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCategoryRequest) Reset()         { *m = AddCategoryRequest{} }
func (m *AddCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCategoryRequest) ProtoMessage()    {}
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{18}
}

func (m *AddCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryRequest.Unmarshal(m, b)
}
func (m *AddCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryRequest.Marshal(b, m, deterministic)
}
func (m *AddCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryRequest.Merge(m, src)
}
func (m *AddCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCategoryRequest.Size(m)
}
func (m *AddCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryRequest proto.InternalMessageInfo

type AddCategoryReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCategoryReply) Reset()         { *m = AddCategoryReply{} }
func (m *AddCategoryReply) String() string { return proto.CompactTextString(m) }
func (*AddCategoryReply) ProtoMessage()    {}
func (*AddCategoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{19}
}

func (m *AddCategoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryReply.Unmarshal(m, b)
}
func (m *AddCategoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryReply.Marshal(b, m, deterministic)
}
func (m *AddCategoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryReply.Merge(m, src)
}
func (m *AddCategoryReply) XXX_Size() int {
	return xxx_messageInfo_AddCategoryReply.Size(m)
}
func (m *AddCategoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryReply proto.InternalMessageInfo

type UpdateCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{20}
}

func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(m, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

type UpdateCategoryReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryReply) Reset()         { *m = UpdateCategoryReply{} }
func (m *UpdateCategoryReply) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryReply) ProtoMessage()    {}
func (*UpdateCategoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{21}
}

func (m *UpdateCategoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryReply.Unmarshal(m, b)
}
func (m *UpdateCategoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryReply.Marshal(b, m, deterministic)
}
func (m *UpdateCategoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryReply.Merge(m, src)
}
func (m *UpdateCategoryReply) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryReply.Size(m)
}
func (m *UpdateCategoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryReply proto.InternalMessageInfo

type DeleteCategoryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryRequest) Reset()         { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()    {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{22}
}

func (m *DeleteCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryRequest.Merge(m, src)
}
func (m *DeleteCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryRequest.Size(m)
}
func (m *DeleteCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryRequest proto.InternalMessageInfo

type DeleteCategoryReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryReply) Reset()         { *m = DeleteCategoryReply{} }
func (m *DeleteCategoryReply) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryReply) ProtoMessage()    {}
func (*DeleteCategoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{23}
}

func (m *DeleteCategoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryReply.Unmarshal(m, b)
}
func (m *DeleteCategoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryReply.Marshal(b, m, deterministic)
}
func (m *DeleteCategoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryReply.Merge(m, src)
}
func (m *DeleteCategoryReply) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryReply.Size(m)
}
func (m *DeleteCategoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryReply proto.InternalMessageInfo

type GetCatChildesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCatChildesRequest) Reset()         { *m = GetCatChildesRequest{} }
func (m *GetCatChildesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCatChildesRequest) ProtoMessage()    {}
func (*GetCatChildesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{24}
}

func (m *GetCatChildesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCatChildesRequest.Unmarshal(m, b)
}
func (m *GetCatChildesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCatChildesRequest.Marshal(b, m, deterministic)
}
func (m *GetCatChildesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCatChildesRequest.Merge(m, src)
}
func (m *GetCatChildesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCatChildesRequest.Size(m)
}
func (m *GetCatChildesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCatChildesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCatChildesRequest proto.InternalMessageInfo

type GetCatChildesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCatChildesReply) Reset()         { *m = GetCatChildesReply{} }
func (m *GetCatChildesReply) String() string { return proto.CompactTextString(m) }
func (*GetCatChildesReply) ProtoMessage()    {}
func (*GetCatChildesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_05a86e58ee60f261, []int{25}
}

func (m *GetCatChildesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCatChildesReply.Unmarshal(m, b)
}
func (m *GetCatChildesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCatChildesReply.Marshal(b, m, deterministic)
}
func (m *GetCatChildesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCatChildesReply.Merge(m, src)
}
func (m *GetCatChildesReply) XXX_Size() int {
	return xxx_messageInfo_GetCatChildesReply.Size(m)
}
func (m *GetCatChildesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCatChildesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCatChildesReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.GetRequest")
	proto.RegisterType((*GetReply)(nil), "pb.GetReply")
	proto.RegisterType((*AddRequest)(nil), "pb.AddRequest")
	proto.RegisterType((*AddReply)(nil), "pb.AddReply")
	proto.RegisterType((*SetCompleteRequest)(nil), "pb.SetCompleteRequest")
	proto.RegisterType((*SetCompleteReply)(nil), "pb.SetCompleteReply")
	proto.RegisterType((*RemoveCompleteRequest)(nil), "pb.RemoveCompleteRequest")
	proto.RegisterType((*RemoveCompleteReply)(nil), "pb.RemoveCompleteReply")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "pb.DeleteReply")
	proto.RegisterType((*UpdateRequest)(nil), "pb.UpdateRequest")
	proto.RegisterType((*UpdateReply)(nil), "pb.UpdateReply")
	proto.RegisterType((*SetStarRequest)(nil), "pb.SetStarRequest")
	proto.RegisterType((*SetStarReply)(nil), "pb.SetStarReply")
	proto.RegisterType((*GetChildrenRequest)(nil), "pb.GetChildrenRequest")
	proto.RegisterType((*GetChildrenReply)(nil), "pb.GetChildrenReply")
	proto.RegisterType((*GetCategoryRequest)(nil), "pb.GetCategoryRequest")
	proto.RegisterType((*GetCategoryReply)(nil), "pb.GetCategoryReply")
	proto.RegisterType((*AddCategoryRequest)(nil), "pb.AddCategoryRequest")
	proto.RegisterType((*AddCategoryReply)(nil), "pb.AddCategoryReply")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "pb.UpdateCategoryRequest")
	proto.RegisterType((*UpdateCategoryReply)(nil), "pb.UpdateCategoryReply")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "pb.DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryReply)(nil), "pb.DeleteCategoryReply")
	proto.RegisterType((*GetCatChildesRequest)(nil), "pb.GetCatChildesRequest")
	proto.RegisterType((*GetCatChildesReply)(nil), "pb.GetCatChildesReply")
}

func init() {
	proto.RegisterFile("todo/pkg/grpc/pb/todo.proto", fileDescriptor_05a86e58ee60f261)
}

var fileDescriptor_05a86e58ee60f261 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0xa5, 0x73, 0xe9, 0x39, 0x9a, 0xb6, 0x69, 0x71, 0x6f, 0x10, 0x76, 0x65, 0x8b, 0x1a,
	0x09, 0x96, 0xac, 0xa2, 0x56, 0xea, 0xbe, 0x85, 0x07, 0x68, 0xb0, 0x55, 0x10, 0x29, 0x36, 0xa9,
	0x41, 0xca, 0x0b, 0xf3, 0x1c, 0x68, 0x32, 0x4e, 0x62, 0x3b, 0x5e, 0xe6, 0xff, 0xbf, 0xb1, 0x7c,
	0xf9, 0x14, 0xb8, 0xd6, 0x92, 0xcb, 0x44, 0xbd, 0x1d, 0x93, 0x63, 0xa1, 0x9e, 0x13, 0x95, 0x25,
	0x18, 0xac, 0x54, 0x21, 0xb5, 0x64, 0xbf, 0x54, 0xb6, 0x1c, 0x00, 0x6c, 0x85, 0xde, 0x89, 0x8f,
	0x4f, 0x71, 0xd6, 0x4b, 0x80, 0xff, 0xd5, 0x97, 0xca, 0x4b, 0x6c, 0x52, 0xce, 0xad, 0xa6, 0xfa,
	0xc2, 0x66, 0x0a, 0x6c, 0x2f, 0xf4, 0x5a, 0x9e, 0x54, 0x2e, 0xb4, 0xa8, 0x09, 0x06, 0x63, 0x27,
	0x45, 0x72, 0x01, 0xb3, 0x9d, 0x38, 0xc9, 0x2f, 0xe1, 0xc3, 0x33, 0x98, 0xf8, 0x05, 0xf2, 0x23,
	0x18, 0x6e, 0x84, 0xcd, 0x0d, 0xa1, 0x5f, 0x07, 0xa6, 0x7f, 0x52, 0xfc, 0xe0, 0xf4, 0x75, 0x80,
	0xfd, 0x18, 0xa2, 0xbd, 0xd0, 0x7b, 0x7d, 0x28, 0x6a, 0x20, 0x82, 0x41, 0x93, 0x98, 0xbd, 0x6f,
	0x85, 0x5e, 0xbf, 0xbc, 0xe6, 0xbc, 0x10, 0xef, 0xd6, 0xde, 0x9d, 0xd4, 0x22, 0x0f, 0x5a, 0x1c,
	0x65, 0x51, 0x7a, 0x64, 0x93, 0x1a, 0x32, 0xe5, 0x3c, 0x40, 0x3a, 0xa9, 0xb9, 0x0f, 0xda, 0xae,
	0x0f, 0xcf, 0x60, 0xe2, 0x17, 0x86, 0xa7, 0xe3, 0x07, 0x78, 0xbf, 0x40, 0x7e, 0x0e, 0x53, 0xda,
	0x5d, 0x75, 0x14, 0x71, 0xae, 0xf1, 0xe6, 0x2c, 0x4d, 0xae, 0xf2, 0xf2, 0xee, 0xfb, 0x2f, 0xfc,
	0x79, 0x94, 0x5c, 0xb2, 0x1b, 0xf8, 0xbd, 0x15, 0x9a, 0x45, 0x2b, 0x95, 0xad, 0x5a, 0x1b, 0xe2,
	0x41, 0xf3, 0xad, 0xf2, 0x12, 0xa1, 0x94, 0x73, 0x82, 0x5a, 0x31, 0x08, 0xaa, 0xd5, 0x60, 0x0f,
	0xd0, 0xb7, 0x24, 0x60, 0x73, 0x2c, 0xbb, 0xae, 0xc4, 0xd3, 0x4e, 0x8e, 0xc3, 0x1b, 0x88, 0x5c,
	0x29, 0xd8, 0x15, 0x72, 0x41, 0x83, 0xe2, 0x45, 0xa8, 0xc2, 0x55, 0x6e, 0xa1, 0x47, 0x57, 0xc3,
	0x2e, 0x10, 0x71, 0x7c, 0x8a, 0x47, 0x76, 0x64, 0x68, 0xba, 0x78, 0xa2, 0x1d, 0xbb, 0x88, 0xb6,
	0xfc, 0x62, 0x09, 0xfc, 0x33, 0x36, 0x31, 0x66, 0x8e, 0x60, 0xc9, 0x16, 0x8f, 0x9d, 0xcc, 0xdc,
	0x87, 0x25, 0x16, 0xdd, 0x47, 0xd7, 0x3f, 0xba, 0x0f, 0xdf, 0xc0, 0x7a, 0xd8, 0xbc, 0x70, 0x3b,
	0xec, 0xba, 0xd0, 0x0e, 0xdb, 0x2a, 0xe0, 0xb0, 0xa5, 0x1f, 0x0d, 0x77, 0x2d, 0xa5, 0x61, 0xdf,
	0x53, 0x7c, 0x09, 0x57, 0x47, 0x7a, 0x89, 0xa0, 0xbb, 0xf4, 0x12, 0x01, 0x7b, 0x71, 0x15, 0x57,
	0x52, 0x5a, 0x25, 0x68, 0x34, 0xad, 0x12, 0x70, 0x9a, 0xa5, 0x30, 0x74, 0xdc, 0x65, 0x97, 0xed,
	0x79, 0x5d, 0xcd, 0xe3, 0x79, 0xa0, 0x51, 0x79, 0x99, 0xf5, 0xaa, 0xff, 0xdd, 0xfd, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc5, 0xc0, 0x5b, 0x53, 0x0e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error)
	SetComplete(ctx context.Context, in *SetCompleteRequest, opts ...grpc.CallOption) (*SetCompleteReply, error)
	RemoveComplete(ctx context.Context, in *RemoveCompleteRequest, opts ...grpc.CallOption) (*RemoveCompleteReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error)
	SetStar(ctx context.Context, in *SetStarRequest, opts ...grpc.CallOption) (*SetStarReply, error)
	GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenReply, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryReply, error)
	AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryReply, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryReply, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryReply, error)
	GetCatChildes(ctx context.Context, in *GetCatChildesRequest, opts ...grpc.CallOption) (*GetCatChildesReply, error)
}

type todoClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoClient(cc grpc.ClientConnInterface) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddReply, error) {
	out := new(AddReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) SetComplete(ctx context.Context, in *SetCompleteRequest, opts ...grpc.CallOption) (*SetCompleteReply, error) {
	out := new(SetCompleteReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/SetComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) RemoveComplete(ctx context.Context, in *RemoveCompleteRequest, opts ...grpc.CallOption) (*RemoveCompleteReply, error) {
	out := new(RemoveCompleteReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/RemoveComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateReply, error) {
	out := new(UpdateReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) SetStar(ctx context.Context, in *SetStarRequest, opts ...grpc.CallOption) (*SetStarReply, error) {
	out := new(SetStarReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/SetStar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenReply, error) {
	out := new(GetChildrenReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/GetChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryReply, error) {
	out := new(GetCategoryReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*AddCategoryReply, error) {
	out := new(AddCategoryReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryReply, error) {
	out := new(UpdateCategoryReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryReply, error) {
	out := new(DeleteCategoryReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/DeleteCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetCatChildes(ctx context.Context, in *GetCatChildesRequest, opts ...grpc.CallOption) (*GetCatChildesReply, error) {
	out := new(GetCatChildesReply)
	err := c.cc.Invoke(ctx, "/pb.Todo/GetCatChildes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	Add(context.Context, *AddRequest) (*AddReply, error)
	SetComplete(context.Context, *SetCompleteRequest) (*SetCompleteReply, error)
	RemoveComplete(context.Context, *RemoveCompleteRequest) (*RemoveCompleteReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	Update(context.Context, *UpdateRequest) (*UpdateReply, error)
	SetStar(context.Context, *SetStarRequest) (*SetStarReply, error)
	GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenReply, error)
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryReply, error)
	AddCategory(context.Context, *AddCategoryRequest) (*AddCategoryReply, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*UpdateCategoryReply, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryReply, error)
	GetCatChildes(context.Context, *GetCatChildesRequest) (*GetCatChildesReply, error)
}

// UnimplementedTodoServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (*UnimplementedTodoServer) Get(ctx context.Context, req *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedTodoServer) Add(ctx context.Context, req *AddRequest) (*AddReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedTodoServer) SetComplete(ctx context.Context, req *SetCompleteRequest) (*SetCompleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetComplete not implemented")
}
func (*UnimplementedTodoServer) RemoveComplete(ctx context.Context, req *RemoveCompleteRequest) (*RemoveCompleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveComplete not implemented")
}
func (*UnimplementedTodoServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedTodoServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedTodoServer) SetStar(ctx context.Context, req *SetStarRequest) (*SetStarReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStar not implemented")
}
func (*UnimplementedTodoServer) GetChildren(ctx context.Context, req *GetChildrenRequest) (*GetChildrenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildren not implemented")
}
func (*UnimplementedTodoServer) GetCategory(ctx context.Context, req *GetCategoryRequest) (*GetCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategory not implemented")
}
func (*UnimplementedTodoServer) AddCategory(ctx context.Context, req *AddCategoryRequest) (*AddCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCategory not implemented")
}
func (*UnimplementedTodoServer) UpdateCategory(ctx context.Context, req *UpdateCategoryRequest) (*UpdateCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (*UnimplementedTodoServer) DeleteCategory(ctx context.Context, req *DeleteCategoryRequest) (*DeleteCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (*UnimplementedTodoServer) GetCatChildes(ctx context.Context, req *GetCatChildesRequest) (*GetCatChildesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatChildes not implemented")
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_SetComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).SetComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/SetComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).SetComplete(ctx, req.(*SetCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_RemoveComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).RemoveComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/RemoveComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).RemoveComplete(ctx, req.(*RemoveCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_SetStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).SetStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/SetStar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).SetStar(ctx, req.(*SetStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/GetChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetChildren(ctx, req.(*GetChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).AddCategory(ctx, req.(*AddCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/DeleteCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetCatChildes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatChildesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetCatChildes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Todo/GetCatChildes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetCatChildes(ctx, req.(*GetCatChildesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Todo_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Todo_Add_Handler,
		},
		{
			MethodName: "SetComplete",
			Handler:    _Todo_SetComplete_Handler,
		},
		{
			MethodName: "RemoveComplete",
			Handler:    _Todo_RemoveComplete_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Todo_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Todo_Update_Handler,
		},
		{
			MethodName: "SetStar",
			Handler:    _Todo_SetStar_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _Todo_GetChildren_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _Todo_GetCategory_Handler,
		},
		{
			MethodName: "AddCategory",
			Handler:    _Todo_AddCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _Todo_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Todo_DeleteCategory_Handler,
		},
		{
			MethodName: "GetCatChildes",
			Handler:    _Todo_GetCatChildes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo/pkg/grpc/pb/todo.proto",
}
